=== jlumbroso/python-slack-scim/json-schema/v1/Group.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Group",
  "definitions": {
    "Group": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "schemas": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "string"
        },
        "displayName": {
          "type": "string"
        },
        "members": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Member"
          }
        },
        "meta": {
          "$ref": "#/definitions/Meta"
        }
      },
      "required": [
        "displayName",
        "id",
        "members",
        "meta",
        "schemas"
      ],
      "title": "Group"
    },
    "Member": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "value": {
          "type": "string"
        },
        "display": {
          "type": "string"
        }
      },
      "required": [
        "display",
        "value"
      ],
      "title": "Member"
    },
    "Meta": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "created": {
          "type": "string"
        },
        "location": {
          "type": "string",
          "format": "uri",
          "qt-uri-protocols": [
            "https"
          ]
        }
      },
      "required": [
        "created",
        "location"
      ],
      "title": "Meta"
    }
  }
}

=== jlumbroso/python-slack-scim/tests/fixture/v1_group_3.json
{
  "schemas": [
    "urn:scim:schemas:core:1.0"
  ],
  "id": "S333",
  "displayName": "test-group-333",
  "members": [
    {
      "value": "M333",
      "display": "Michael Jackson"
    }
  ],
  "meta": {
    "created": "2019-03-18T09:05:06-07:00",
    "location": "https:\/\/api.slack.com\/scim\/v1\/Groups\/S333"
  }
}
